# Generated by Django 3.2.20 on 2023-08-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_name', models.CharField(max_length=50)),
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.DecimalField(decimal_places=0, max_digits=1)),
                ('remaining_seats', models.DecimalField(decimal_places=0, max_digits=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
