# Generated by Django 3.2.20 on 2023-08-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='remaining_seats',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='trip',
            name='seats',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
