# Generated by Django 3.2.20 on 2023-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0002_auto_20230801_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('userid', models.DecimalField(decimal_places=0, max_digits=3)),
                ('trip_id', models.DecimalField(decimal_places=0, max_digits=3)),
                ('trip_name', models.CharField(max_length=50)),
                ('seats', models.DecimalField(decimal_places=0, max_digits=2)),
                ('remaining_seats', models.DecimalField(decimal_places=2, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
            ],
        ),
    ]
