# Generated by Django 3.2.20 on 2023-08-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0003_booking_seats_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_required',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
