# Generated by Django 3.2.20 on 2023-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='remaining_seats',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
