# Generated by Django 3.2.20 on 2023-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0005_alter_booking_seats_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_required',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='remaining_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
