# Generated by Django 3.2.20 on 2023-08-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0006_auto_20230803_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.IntegerField(),
        ),
    ]
