# Generated by Django 3.2.20 on 2023-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0008_auto_20230803_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats_required',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
