# Generated by Django 3.2.20 on 2023-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0010_auto_20230803_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='seats',
            field=models.IntegerField(default=80),
        ),
    ]
