# Generated by Django 3.2.20 on 2023-08-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0012_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='remaining_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
