# Generated by Django 3.2.20 on 2023-08-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Football_travel', '0014_alter_trip_remaining_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
